# Prácticas de pandas

### Importamos pandas y numpy

In [2]:
import numpy as np
import pandas as pd

### Leer del disco un fichero utilizando ',' como separador

In [3]:
df = pd.read_csv('iris.csv', sep=',')

In [9]:
#Extraer el nombre de las columnas del dataframe
print(df.columns)

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'class'],
      dtype='object')


### Prácticas de filtros

In [7]:
# Extraer solo las entradas cuya clase sea 0
df_0 = df[df['class']==0].copy()
print('número de líneas', df_0.shape[0])

número de líneas 50


In [18]:
# Averiguar cuál es el valor máximo y mínimo del sepal length
s_l_max = df['sepal length (cm)'].max()
print('sepal length max =', s_l_max)
s_l_min = df['sepal length (cm)'].min()
print('sepal length min =', s_l_min)
s_l_med = df['sepal length (cm)'].mean()
print('sepal length med =', s_l_med)
s_l_des_es = df['sepal length (cm)'].std()
print('sepal length standard deviation =', s_l_des_es)

sepal length max = 7.9
sepal length min = 4.3
sepal length med = 5.843333333333335
sepal length standard deviation = 0.8280661279778629


In [17]:
# Extraer solo las entradas cuyo sepal length sea mayor que la media
s_l_med = df['sepal length (cm)'].mean()
df_med = df[df['sepal length (cm)']>s_l_med].copy()
print('número de líneas', df_med.shape[0])


número de líneas 70


In [22]:
#Extraer las entradas cuyo sepal length sea mayor que la media y cuya clase sea 2
s_l_med = df['sepal length (cm)'].mean()
df_med = df[df['sepal length (cm)']>s_l_med].copy()
df_med_2 = df_med[df_med['class']==2].copy()
print('número de líneas', df_med_2.shape[0])
#Otra forma más rápida de hacerlo
df_med_2 = df[(df['class']==2) & (df['sepal length (cm)']>df['sepal length (cm)'].mean())].copy()
print('número de líneas 2.0', df_med_2.shape[0])

número de líneas 44
número de líneas 2.0 44


In [23]:
#Extraer las entradas cuyo sepal length sea mayor que la media o cuya clase sea 2
df_med_2 = df[(df['class']==2) | (df['sepal length (cm)']>df['sepal length (cm)'].mean())].copy()
print('número de líneas', df_med_2.shape[0])

número de líneas 76


### Extraer datos a listas

In [ ]:
# Crear una lista con los valores de sepal length para las flores de clase 0
df_0 = df[df['class']==0].copy()
df_0_list = df_0['sepal length (cm)'].tolist()
print('lista de los sepal length de las flores de clase 0 =', df_0_list)

### Extraer datos a numpy arrays

In [26]:
#Crear un numpy array con los valores de sepal length para las flores de clase 0
df_0 = df[df['class']==0].copy()
df_0_numpy = df_0['sepal length (cm)'].to_numpy()
print('numpy array de los sepal length de las flores de clase 0 =', df_0_numpy)

numpy array de los sepal length de las flores de clase 0 = [5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5. ]


In [27]:
#Crear un numy array con los valores de todas las columnas de características
df_0 = df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)','petal width (cm)']].copy()
df_0_numpy = df_0.to_numpy()
print('numpy array de las columnas de atributos =', df_0_numpy)

numpy array de las columnas de atributos = [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3